language: php
php:
  - "5.3"
  - "5.4"
  - "5.5"
before_script:
  - mysql -u root -e "create database fedora;"
  - mysql -u root -e "GRANT ALL PRIVILEGES ON fedora.* To 'fedora'@'localhost' IDENTIFIED BY 'fedora';"
  - git clone git://github.com/islandora/islandora_tomcat.git
  - cd islandora_tomcat
  - export CATALINA_HOME='.'
  - ./bin/startup.sh
  - cd ..
  - sleep 10
script:
  - phpunit -c tests/travis.xml tests/
